In [1]:
import tensorflow as tf


In [2]:
# This is statements are because tensorflow will not use all the VRAM of gpu 
physical_device = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_device[0],True)


## Intialization of a tensor

In [9]:
tf.constant(3,shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])>

In [10]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [12]:
tf.eye(num_rows=3) # to create identity matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [16]:
# tensors according to the distribution
print(tf.random.uniform((1,3),minval=0, maxval=1))
print(tf.random.normal((1,3),mean=0,stddev=1))

tf.Tensor([[0.91778374 0.83363104 0.6384499 ]], shape=(1, 3), dtype=float32)
tf.Tensor([[ 0.40683028  0.31994724 -0.22076283]], shape=(1, 3), dtype=float32)


In [19]:
x = tf.range(0,10,delta=2) # just like range function in the python

## Mathematical operation

In [20]:
# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x - y

z = tf.divide(x, y)
z = x / y

z = tf.multiply(x, y)
z = x * y

z = tf.tensordot(x, y, axes=1)

z = x ** 5

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
z = x @ y

## Indexing 

In [3]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)

x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])


tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Reshaping

In [4]:
x = tf.range(9)

x = tf.reshape(x, (3, 3))

x = tf.transpose(x, perm=[1, 0])