## Question 1
Q1. What are the benefits of the built-in array package, if any?

### Answer
* unlike Python List, the Array is much more rigid. That is, the items that an array contains must be of the same type. Therefore, the size of the item will also be the same. We can check the size of each item
* Since the type code is very important to an array, which determined what kind of elements that the array can have. We can get the type code by accessing its property typecode
* as python list uses more size then python array module it is more efficient use of the memory if we use array if situation demands efficient use of the memory

## Question 2
Q2. What are some of the array package&#39;s limitations?

### Answer
it has shortage of mathematical functions like numpy and does not have flexibility like list i.e array only contains similar data type .

## Question 3
Q3. Describe the main differences between the array and numpy packages.

### Answer
* NumPy arrays should be smaller memory
* numpy provides more mathematical functions then array .
* there are other type of standard numpy operations which is not supported by array which makes numpy easy to use.
* most of the important library uses numpy at the backend or mimc there functions (like Tensors) so practicing numpy operations gives you general idea of the operation which other library might have if they use numpy in the backend

## Question 4
Q4. Explain the distinctions between the empty, ones, and zeros functions.

### Answer
* empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.
* zeros functions is used to intialise an array with zeros which specified shape
* ones functions is used to intialise an array with ones which specified shape

## Question 5
Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable
argument?

### Answer

Construct an array by executing a function over each coordinate.

The resulting array therefore has a value fn(x, y, z) at coordinate (x, y, z).
```python 
import numpy as np
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
```


## Question 6
Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as
an int or a floating-point value) through addition, as in the expression A + n?

### Answer
it adds single value to all the elements of numpy array 

## Question 7
Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)?
What is the outcome?

### Answer


yes it is inplace operations where original variable is changed

```python 
import numpy as np

a = np.ones((5,5))
a +=1

# Output
# array([[2., 2., 2., 2., 2.],
#        [2., 2., 2., 2., 2.],
#        [2., 2., 2., 2., 2.],
#        [2., 2., 2., 2., 2.],
#        [2., 2., 2., 2., 2.]])
```

## Question 8
Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to
one of these arrays?

### Answer
you cannot change the character assign it using indexing if you try you will get IndexError
```python
import numpy as np

a = np.array('ineuron')

a[0] = 'o'
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```

## Question 9
Q9. What happens when you combine two numpy arrays using an operation like addition (+) or
multiplication (*)? What are the conditions for combining two numpy arrays?

### Answer
elements wise additions or multiplications can only happen if same axis matches example for 2 dimensional matrix row and row should match or column and column should match

Note: actually the dimesion of both the variable should be same but if same axis matches as the above example the that repeated the other varible axis times.

example

```python
import numpy as np
a = np.ones((5,4))
b = np.ones((5,1))*3
a*b
# output
# array([[3., 3., 3., 3.],
#        [3., 3., 3., 3.],
#        [3., 3., 3., 3.],
#        [3., 3., 3., 3.],
#        [3., 3., 3., 3.]])
```
b is repeated along axis 1 for 4 times


## Question 10
Q10. What is the best way to use a Boolean array to mask another array?

### Answer
to pass it in the indicing example

```python 
import numpy as np
a = np.zeros((5,5))
a[0][1],a[1][1],a[1][0] = 1,1,1
i = a>=1
a[i]

# Output
# array([1., 1., 1.])
```

## Question 11
Q11. What are three different ways to get the standard deviation of a wide collection of data using
both standard Python and its packages? Sort the three of them by how quickly they execute.

### Answer
1. Using formula writing manual scripts to calculate the std and mean
2. using numpy library to calculate standard deviation and mean 
3. converting data to DataFrame and use DataFrame.describe which gives all the standard statistical description.

## Question 12
12. What is the dimensionality of a Boolean mask-generated array?

### Answer
it should be same as the dimension of the array from where it should be masked